DjangoMania/blog/urls.py
from django.urls import path
from blog.views import all_post_view,category_view,tag_view,post_detail_view

app_name = 'blog'

urlpatterns = [
    path('', all_post_view, name='all_post_view'),
    path('category/<slug:category_slug>/', category_view, name='category_view'),
    path('tag/<slug:tag_slug>/', tag_view, name='tag_view'),
    path('category/<slug:category_slug>/<slug:post_slug>', post_detail_view, name='post_detail_view'),

]

DjangoMania/config/urls.py
from django.contrib import admin
from config.views import logout_view 
from django.urls import  path,include
from page.views import home_view

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', home_view,name="home"),
    #Page App
    path('page/', include('page.urls', namespace='page')),
     
    #Todo app
    path('todo/', include('todo.urls', namespace='todo')),
    
    # Blog app
    path('blog/', include('blog.urls', namespace='blog')),

    #Auth:
    path('account/logout/', logout_view,name="logout_view"),

    #TinyMCE
    path('tinymce/', include('tinymce.urls')),
   

    #ADMIN:
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

DjangoMania/templates/core/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TODO APP</title>
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
    {% include 'core/navbar.html' %}

    {% block container-fluid %}
    {% endblock container-fluid %}
    
    <div class="container my-5">
        {% block container %}
        {% endblock container %}
    </div>

    {% include 'core/footer.html' %}
    <!--Bootstrap JS-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

DjangoMania/templates/core/footer.html
<div class="bg-light py-5 mt-5">
    <div class="container">
        <div class="col">
            <h1 class="text-muted">DjangoMania</h1>
        </div>
    </div>
</div>

DjangoMania/templates/core/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark ">
    <div class="container">
        <a class="navbar-brand" href="/">DjangoMania</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Ana Sayfa</a>
                </li>

                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Todo Kategoriler
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in global_todo_categories %}
                        <li>
                            
                            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endif %}
                
                {% for page in global_pages %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{ page.get_absolute_url }}">{{ page.title }}</a>
                </li>
                {% endfor %}

                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'blog:all_post_view' %}">Blog</a>
                </li>

                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'logout_view' %}">Oturumu Kapat</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>